# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Firestripe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Firestripe
  pod 'Stripe', :git => 'https://github.com/stripe/stripe-ios.git', :branch => 'mc-beta-2'

end
